### ISSUE TITLE
Merge Dependabot (axios)

### ISSUE THREAD

**Issue by jodiedoubleday** [franklintarter/gatsby-source-google-places#15]
I've been using this plugin for a while (thank you)

I've just been alerted to a security issue for this plugin and noticed it's in a PR already from Dependabot.
If you still support this plugin would you mind merging this security fix? or advise if you no longer actively support the plugin.

Thanks

**Comment by franklintarter** [comment]
Hi Jodie,

Thanks for reaching out. I am still maintaining it and I will make a TODO
for myself to update those packages. Shouldn't be any longer than a few
days or a week.

I'll let you know when it's done.

**Comment by franklintarter** [comment]
@jodiedoubleday  Just released version `0.0.8` with both dependabot updates.
