### ISSUE TITLE
Question: Are there any plans for this plugin to be updated to support Gatsby V3 or Gatsby V4?

### ISSUE THREAD

**Issue by jodiedoubleday** [franklintarter/gatsby-source-google-places#21]
The plugin seems to still work perfectly on new installs of Gatsby but the Peer Dependencies and Engines still use old versions of Node and Gatsby...
```
"peerDependencies": {
    "gatsby": "^2.0.0"
  },
  "engines": {
    "node": ">=8.0.0"
  }
```

are there any plans to push any releases to update these?
I'm happy to look into creating a Pull Request for the work but, I'm a relatively junior developer.

**Comment by PaulFelge** [comment]
I would love to see that as well! =)

**Comment by franklintarter** [comment]
Hey, thanks for the suggestion! If either of you would like to make a PR for this I'd be happy to test, merge and release it for you. If not I will try to get around to this when I can but can't promise a timeline 🙏 

I imagine Gatsby might have some upgrade steps for this somewhere. I just don't know cause I haven't made a Gatsby project for a bit.

**Comment by jdeola** [comment]
I think with this plug-in has finally stopped working with Gatsby v4, even when using --legacy-peer-deps.

Is anyone else having issues?

**Comment by franklintarter** [comment]
@jdeola @PaulFelge @jodiedoubleday 

I just got around to this. I followed the migration doc on Gatsby – https://v4.gatsbyjs.com/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4/

I made this PR – https://github.com/franklintarter/gatsby-source-google-places/pull/22

I pushed an NPM update – https://www.npmjs.com/package/gatsby-source-google-places – please update to version 1.0.0

I tested with my local example app and it worked for me. Please try it out and let me know if you have any issues, or re-open this issue. Cheers 🥂
