### ISSUE TITLE
Gatsby build fails when gatsby-source-google-places plugin is installed.

### ISSUE THREAD

**Issue by nanoDevFabrice** [franklintarter/gatsby-source-google-places#29]
Gatsby build fails when `**gatsby-source-google-places**` plugin is installed.
When it tries to loop place.reviews it fails.
![935EDB2D-D550-457D-AFCF-88A6396B9775](https://user-images.githubusercontent.com/104977325/184916093-2fe683ff-7b46-4660-a9ea-d7e1d27c8769.jpeg)
From what I have on my terminal, place.reviews is undefined
![D9096572-4AF3-4613-B2EE-A330475A7E8E](https://user-images.githubusercontent.com/104977325/184916108-04548c42-a490-4e07-9ced-8d9c9bd3bdb0.jpeg)

**Comment by franklintarter** [comment]
resolved on https://github.com/franklintarter/gatsby-source-google-places/pull/35
published 1.0.3 on npm
