### ISSUE TITLE
Fetch multiple places?

### ISSUE THREAD

**Issue by hartey11** [franklintarter/gatsby-source-google-places#6]
Hi, Is it possible to fetch more than 1 place? I have 2 places that I'd like to get info for. I've tried putting the places ID's in an array in the config but it seems to only return the first one.

**Comment by franklintarter** [comment]
@hartey11 
Please review linked PR and let me know if you think that will work for your use case.

Thank you

**Comment by franklintarter** [comment]
@hartey11 
merged and updated in NPM
use version
`    "gatsby-source-google-places": "^0.0.5"`
