### ISSUE TITLE
TypeError: Cannot set property 'id' of undefined

### ISSUE THREAD

**Issue by hartey11** [franklintarter/gatsby-source-google-places#8]
Hey @franklintarter sorry I know I said I got this working but it looks like it only worked with `gatsby develop`. I've since tried to deploy to netlify (also using clear cache and deploy site) and I'm still getting the same error. This is also true when I run `gatsby build` locally.

```
### package.json
{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby",
  "version": "0.1.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "@emotion/core": "^10.0.27",
    "@emotion/styled": "^10.0.27",
    "eslint-plugin-emotion": "^10.0.27",
    "eslint-plugin-react-redux": "^3.0.3",
    "gatsby": "^2.19.1",
    "gatsby-image": "^2.2.39",
    "gatsby-plugin-emotion": "^4.1.21",
    "gatsby-plugin-manifest": "^2.2.37",
    "gatsby-plugin-offline": "^3.0.32",
    "gatsby-plugin-react-helmet": "^3.1.21",
    "gatsby-plugin-react-redux": "^1.1.0-0",
    "gatsby-plugin-sharp": "^2.4.0",
    "gatsby-source-filesystem": "^2.1.46",
    "gatsby-source-google-places": "^0.0.5",
    "gatsby-transformer-sharp": "^2.3.13",
    "is-url-external": "^1.0.3",
    "normalize.css": "^8.0.1",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-helmet": "^5.2.1",
    "react-id-swiper": "^3.0.0",
    "react-inlinesvg": "^1.2.0",
    "react-instafeed": "^1.0.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "swiper": "^5.3.6",
    "typeface-orbitron": "^1.1.3",
    "use-abortable-fetch": "^2.6.11",
    "use-ssr": "^1.0.22",
    "uuid": "^7.0.3"
  },
  "devDependencies": {
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-prettier": "^6.9.0",
    "eslint-plugin-import": "^2.20.0",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-react": "^7.18.0",
    "eslint-plugin-react-hooks": "^3.0.0",
    "prettier": "^2.0.2"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}

### gatsby-config.js
const menus = require("./gatsby/menus");

module.exports = {
  siteMetadata: {
    title: "Gatsby Default Starter",
    description: "Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.",
    author: "@gatsbyjs",
    menus,
  },
  plugins: [
    "gatsby-plugin-react-helmet",
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "images",
        path: "${__dirname}/src/images",
      },
    },
    "gatsby-transformer-sharp",
    "gatsby-plugin-sharp",
    {
      resolve: "gatsby-plugin-manifest",
      options: {
        name: "gatsby-starter-default",
        short_name: "starter",
        start_url: "/",
        background_color: "#663399",
        theme_color: "#663399",
        display: "minimal-ui",
        icon: "src/images/gatsby-icon.png",
      },
    },
    {
      resolve: "gatsby-plugin-react-redux",
      options: {
        pathToCreateStoreModule: "./src/state/createStore",
        serialize: {
          space: 0,
          isJSON: true,
          unsafe: false,
        },
        cleanupOnClient: true,
        windowKey: "__PRELOADED_STATE__",
      },
    },
    {
      resolve: "gatsby-plugin-emotion",
      options: {},
    },
    {
      resolve: "gatsby-source-google-places",
      options: {
        placeIds: [
          "ChIJ8-0CIs4adkgRFAs5L2t2Q0k",
          "ChIJdda2YaENdkgRCwEXWRSTFyw",
        ],
        apiKey: "...",
      },
    },
  ],
};

```

**Comment by franklintarter** [comment]
I just tested with a brand new gatsby default starter and it worked fine with both `gatsby develop` and `gatsby build`. I'm not sure what else to tell you other than that it smells like an npm/yarn caching issue where you've still got the old package somehow. It's odd that it happens to you both on Netlify and on locally when you build.

Try running through `yarn cache clean` and `gatsby clean` if you haven't already.

I'd like to help you with this I need help reproducing it. Would you create a fresh repo from `gatsby new default` that reproduces, and link it here (sans API key)? I can pull it and see if I can experience the issue. It really does smell like a caching issue, but linking me to the fresh repo would help rule anything else out.

**Comment by hartey11** [comment]
@franklintarter yeah I'm at a bit of a loss. Its working fine for me now locally (both develop and build) but I'm still getting the error on netlify, even after deleting my site and starting again.

**Comment by franklintarter** [comment]
@hartey11 
Bummer. Maybe something funky happened with your `yarn.lock` or `package.json.lock`? You could try deleting those and running `yarn` or `npm install` to regenerate them. Then inspect them to make sure they're referencing the `0.0.5` version of this package. Then commit them to see if it helps Netlify pull the right version.

**Comment by hartey11** [comment]
@franklintarter made some small progress... been able to confirm that netlify is getting the latest version 0.0.5. 

So I'm guessing something is stopping the response from being received correctly by netlify. I can see errors are being output to the console from the promise, so maybe google is returning something else or in a different format?

Here's a link to issue I opened on netlify for reference:
https://community.netlify.com/t/updating-node-modules/12087/16

**Comment by franklintarter** [comment]
@hartey11 
Interesting. So the old package thing could have been a red herring. I will try my own Netlify deployment a bit later this week and let you know if I can encounter the same issue.

**Comment by franklintarter** [comment]
@hartey11 
I stumbled upon what I think could be your issue!

The message you are getting is a red herring. The call to the google API is failing. I would guess the reason is that your API key is not getting set correctly in the Netlify environment. I also forgot to set up my API key and got the same error you've been getting.

I'm going to update the package so that errors from the Google API will get rethrown and the messages can be seen appropriately.

**Comment by franklintarter** [comment]
@hartey11 
Okay, I updated the package handle errors from the API so you should see them in the console. Please try `yarn add gatsby-source-google-places` to update the package to version `0.0.6`. Hopefully, you'll see something helpful in your console that will help debug your Netlify issue.

Let me know how that goes.

![image](https://user-images.githubusercontent.com/13702933/79382864-10252080-7f19-11ea-9a3c-027ae71c4157.png)

**Comment by hartey11** [comment]
@franklintarter you've only gone and sorted it! I was able to debug it straight away with the added handle errors. Turns out there was an issue with my Google Cloud billing account that needed resolving, which I've now fixed and been able to successfully deploy. Not sure why the API key was still working locally though... lol

Thanks for all your help!

**Comment by franklintarter** [comment]
Woohoo!
